// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homescreen/DesignAnalysis.tsx": () => import("../components/mockups/homescreen/DesignAnalysis.tsx"),
  "./components/mockups/homescreen/DesktopRedesign.tsx": () => import("../components/mockups/homescreen/DesktopRedesign.tsx"),
  "./components/mockups/homescreen/MobileCurrent.tsx": () => import("../components/mockups/homescreen/MobileCurrent.tsx")
};
